<a href="https://colab.research.google.com/github/steffenmodest/Python_Examples/blob/Protocol/M_Net_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os.path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from datetime import datetime

rs = 23  # fester Random Seed

In [2]:
# from google.colab import drive
# drive.mount('/content/drive')

Load Data

In [3]:
from tensorflow.keras.datasets import fashion_mnist, mnist

# Fashion MNIST Daten laden, wir wollen nur die Trainingsdaten und verwerfen die Testdaten
# (X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()
(X_train, y_train), (X_test, y_test) = mnist.load_data()

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(60000, 28, 28)
(10000, 28, 28)
(60000,)
(10000,)


Own Funs

In [4]:
def ifelse(a):
  if a == 0:
    return 1
  else:
    return a


def rms_norm(v_x):
  n_rms = np.sqrt(np.sum(v_x ** 2)/(len(v_x) - 1))
  return v_x/n_rms


def prot_row(d_results):
    """
    make a new row in protokoll

    Parameters
    ----------
    outcome : TYPE
        DESCRIPTION.

    Returns
    -------
    None.

    """
    
    prot_file = 'M-Net_Protocol.xlsx'
    # prot_file = '/content/sample_data/M-Net_Protocol.xlsx'
    if os.path.isfile(prot_file):
        df_prot = pd.read_excel (prot_file)
        df_prot = df_prot.append(d_results, 
                          ignore_index=True)
    else:
        # df_prot = pd.DataFrame.from_dict(d_results)
        df_prot = pd.DataFrame([results])
        # pf_prot = pd.DataFrame.from_records([d_results], index='TIMESTAMP')
        # df_prot = pd.DataFrame(columns=('TIMESTAMP', 
        #                                 'NUMBER_OF_HIDDEN', 
        #                                 'ACCURACY_SCORE', 
        #                                 'MAE_1ST_FL',
        #                                 'MSE_1ST_FL',
        #                                 'R2_1ST_FL',
        #                                 'MAE_1ST_BA',
        #                                 'MSE_1ST_BA',
        #                                 'R2_1ST_BA',
        #                                 'MAE_2ND_FL',
        #                                 'MSE_2ND_FL',
        #                                 'R2_2ND_FL',
        #                                 'MAE_2ND_BA',
        #                                 'MSE_2ND_BA',
        #                                 'R2_2ND_BA',
        #                                 'MSG'))
        
    # s_outcome = outcome.partition('<msg>')[2]
    # s_outcome = s_outcome.partition('</msg>')[0]
    # s_outcome = s_outcome.partition('Set ')[2]
    # s_set = s_outcome.partition(' ')[0]
    # s_msg = s_outcome.partition(' ')[2]
    
    # s_outcome = s_outcome.strip(',()')
    # l_outcome = s_outcome.split(',')
    # df_prot = df_prot.append({'TIMESTAMP':datetime.now(),
    #                           'RESULT': result,
    #                           'SAS_SET':int(s_set),
    #                           'MSG':s_msg,
    #                           'COUNT':n_len}, ignore_index=True)
    
    # df_prot = df_prot.append(d_results, 
    #                          ignore_index=True)
    df_prot.to_excel(prot_file, index=False)
        
    return None

Params and Results

In [5]:
params = {'N_HIDDEN': 10}
results = {'TIMESTAMP': datetime.now(),
           'NUMBER_OF_HIDDEN': params['N_HIDDEN'],
          'ACCURACY_SCORE': 0, 
          'MAE_1ST_FL': 0,
          'MSE_1ST_FL': 0,
          'R2_1ST_FL': 0,
          'MAE_1ST_BA': 0,
          'MSE_1ST_BA': 0,
          'R2_1ST_BA': 0,
          'MAE_2ND_FL': 0,
          'MSE_2ND_FL': 0,
          'R2_2ND_FL': 0,
          'MAE_2ND_BA': 0,
          'MSE_2ND_BA': 0,
          'R2_2ND_BA': 0,
          'MAE_TEST_BA': 0,
          'MSE_TEST_BA': 0,
          'R2_TEST_BA': 0,
          'DICT_REPORT': '',
          'MSG':'M-Net on python'}

In [6]:
results

{'TIMESTAMP': datetime.datetime(2021, 4, 16, 23, 12, 55, 883612),
 'NUMBER_OF_HIDDEN': 10,
 'ACCURACY_SCORE': 0,
 'MAE_1ST_FL': 0,
 'MSE_1ST_FL': 0,
 'R2_1ST_FL': 0,
 'MAE_1ST_BA': 0,
 'MSE_1ST_BA': 0,
 'R2_1ST_BA': 0,
 'MAE_2ND_FL': 0,
 'MSE_2ND_FL': 0,
 'R2_2ND_FL': 0,
 'MAE_2ND_BA': 0,
 'MSE_2ND_BA': 0,
 'R2_2ND_BA': 0,
 'MAE_TEST_BA': 0,
 'MSE_TEST_BA': 0,
 'R2_TEST_BA': 0,
 'DICT_REPORT': '',
 'MSG': 'M-Net on python'}

Preprocess data

In [7]:
prot_row(results)

NEW Norm

In [8]:
X = X_train.reshape(len(X_train), -1).astype('int')
X = pd.DataFrame(X)
X = X.applymap(ifelse)
X = X.apply(rms_norm, axis=1)
X = np.array(X)

In [9]:
X

array([[0.01148061, 0.01148061, 0.01148061, ..., 0.01148061, 0.01148061,
        0.01148061],
       [0.01076957, 0.01076957, 0.01076957, ..., 0.01076957, 0.01076957,
        0.01076957],
       [0.01425251, 0.01425251, 0.01425251, ..., 0.01425251, 0.01425251,
        0.01425251],
       ...,
       [0.01299969, 0.01299969, 0.01299969, ..., 0.01299969, 0.01299969,
        0.01299969],
       [0.01400668, 0.01400668, 0.01400668, ..., 0.01400668, 0.01400668,
        0.01400668],
       [0.01375564, 0.01375564, 0.01375564, ..., 0.01375564, 0.01375564,
        0.01375564]])

In [10]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, Normalizer, MinMaxScaler, FunctionTransformer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Plätte 2D Bild in einen Vektor:
# Reshape behält die Anzahl Element in der ersten Dimension (len(X_orig) -> #Bilder)
# die restlichen Zellen des Arrays (-1 -> Pixel) bekommen alle ihre eigene Dimension
# X = X_train.reshape(len(X_train), -1).astype('float64')

# # Dimensionen um den Mittelpunkt zentrieren
# preproccessing = StandardScaler()
# X = preproccessing.fit_transform(X)
# X = np.array(X)

print ("Originaldaten:")
print("Shape: {}, Mean: {:f}, STD: {:f}".format(X_train.shape, np.mean(X_train), np.std(X_train)))

print ("Vorbereitete Daten:")
print("Shape: {}, Mean: {:f}, STD: {:f}".format(X.shape, np.mean(X), np.std(X)))

Originaldaten:
Shape: (60000, 28, 28), Mean: 33.318421, STD: 78.567490
Vorbereitete Daten:
Shape: (60000, 784), Mean: 0.396041, STD: 0.917538


Create Hidden Activations

In [11]:
H = np.random.rand(60000, params['N_HIDDEN'])
print(H.shape)
print(H)

(60000, 10)
[[0.51199882 0.79209962 0.89410479 ... 0.76735254 0.5282281  0.92742326]
 [0.24833398 0.21328955 0.8465505  ... 0.18923217 0.38287134 0.61052366]
 [0.71379627 0.67007006 0.08354901 ... 0.33061485 0.16229715 0.63615999]
 ...
 [0.30819182 0.83523741 0.25343739 ... 0.1779576  0.67317072 0.24075655]
 [0.1459305  0.05859992 0.38403147 ... 0.39574445 0.54412118 0.48807615]
 [0.83322608 0.51053665 0.2352269  ... 0.84615442 0.86533197 0.17271619]]


1st Forward Learn

In [12]:
import numpy as np
from sklearn.linear_model import LinearRegression

reg = LinearRegression().fit(H, X)
print(reg.score(H, X))
X_pred = reg.predict(H)

results['MAE_1ST_FL'] = round(mean_absolute_error(X_pred, X), 3)
results['MSE_1ST_FL'] = round(mean_squared_error(X_pred, X), 3)
results['R2_1ST_FL'] = round(r2_score(X_pred, X, multioutput="variance_weighted"), 3)

print(f'MAE {mean_absolute_error(X_pred, X)}')
print(f'MSE {mean_squared_error(X_pred, X)}')
print(f'R2 {r2_score(X_pred, X)}')
print(f'R2 vw {r2_score(X_pred, X, multioutput="variance_weighted")}')
print(f'R2 ua {r2_score(X_pred, X, multioutput="uniform_average")}')

W = reg.coef_
print(W.shape)
WI = reg.intercept_
print(WI.shape)

0.00018522488514982716
MAE 0.43775997454043447
MSE 0.5937982569743558
R2 -6790.300958782893
R2 vw -5508.976195508291
R2 ua -6790.300958782893
(784, 10)
(784,)


1st Back Activations

In [13]:
# # X = X_train.reshape(len(X_train), -1).astype('int')
# W = pd.DataFrame(W)
# # X = X.applymap(ifelse)
# W = W.apply(rms_norm)
# W = np.array(X)

In [14]:
XT = X.transpose()
print(f'shape of X_train {X.shape} and X_train transposed {XT.shape}')

reg = LinearRegression().fit(W, XT)
print(reg.score(W, XT))
XT_pred = reg.predict(W)

results['MAE_1ST_BA'] = round(mean_absolute_error(XT_pred, XT), 3)
results['MSE_1ST_BA'] = round(mean_squared_error(XT_pred, XT), 3)
results['R2_1ST_BA'] = round(r2_score(XT_pred, XT, multioutput="variance_weighted"), 3)

print(f'MAE {mean_absolute_error(XT_pred, XT)}')
print(f'MSE {mean_squared_error(XT_pred, XT)}')
print(f'R2 {r2_score(XT_pred, XT)}')
print(f'R2 vw {r2_score(XT_pred, XT, multioutput="variance_weighted")}')
print(f'R2 ua {r2_score(XT_pred, XT, multioutput="uniform_average")}')

H_new = reg.coef_
print(H_new.shape)
HI = reg.intercept_
print(HI.shape)

shape of X_train (60000, 784) and X_train transposed (784, 60000)
0.19942704879920192
MAE 0.5751535870453993
MSE 0.6704785582025172
R2 -3.917118476837708
R2 vw -2.987616296745072
R2 ua -3.917118476837708
(60000, 10)
(60000,)


Hidden Norm

In [15]:
# X = H_new_train.reshape(len(H_new_train), -1).astype('int')
H_new = pd.DataFrame(H_new)
# H_new = H_new.applymap(ifelse)
H_new = H_new.apply(rms_norm, axis=1)
H_new = np.array(H_new)

2nd Forward learn - result are Coherent Weights

In [16]:
reg = LinearRegression().fit(H_new, X)
print(reg.score(H_new, X))
X_pred = reg.predict(H_new)

results['MAE_2ND_FL'] = round(mean_absolute_error(X_pred, X), 3)
results['MSE_2ND_FL'] = round(mean_squared_error(X_pred, X), 3)
results['R2_2ND_FL'] = round(r2_score(X_pred, X, multioutput="variance_weighted"), 3)

print(f'MAE {mean_absolute_error(X_pred, X)}')
print(f'MSE {mean_squared_error(X_pred, X)}')
print(f'R2 {r2_score(X_pred, X)}')
print(f'R2 vw {r2_score(X_pred, X, multioutput="variance_weighted")}')
print(f'R2 ua {r2_score(X_pred, X, multioutput="uniform_average")}')

W = reg.coef_
print(W.shape)
WI = reg.intercept_
print(WI.shape)

0.2085879325513491
MAE 0.33007999324528847
MSE 0.38353793694105576
R2 -41.94903718406265
R2 vw -0.8231754673937641
R2 ua -41.94903718406265
(784, 10)
(784,)


2nd Back Activation - final representation of X_train in Hidden Activations

In [17]:
reg = LinearRegression().fit(W, XT)
print(reg.score(W, XT))
XT_pred = reg.predict(W)

results['MAE_2ND_BA'] = round(mean_absolute_error(XT_pred, XT), 3)
results['MSE_2ND_BA'] = round(mean_squared_error(XT_pred, XT), 3)
results['R2_2ND_BA'] = round(r2_score(XT_pred, XT, multioutput="variance_weighted"), 3)

print(f'MAE {mean_absolute_error(XT_pred, XT)}')
print(f'MSE {mean_squared_error(XT_pred, XT)}')
print(f'R2 vw {r2_score(XT_pred, XT, multioutput="variance_weighted")}')
print(f'R2 ua {r2_score(XT_pred, XT, multioutput="uniform_average")}')

H_new = reg.coef_
print(H_new.shape)
HI = reg.intercept_
print(HI.shape)

0.38818569034280376
MAE 0.5181485526671504
MSE 0.5118462962683661
R2 vw -0.5663691802804929
R2 ua -0.8427834634543515
(60000, 10)
(60000,)


In [18]:
# X = H_new_train.reshape(len(H_new_train), -1).astype('int')
H_new = pd.DataFrame(H_new)
# H_new = H_new.applymap(ifelse)
H_new = H_new.apply(rms_norm, axis=1)
H_new = np.array(H_new)

KNN test with Hidden Activations

In [19]:
X = X_test.reshape(len(X_test), -1).astype('int')
X = pd.DataFrame(X)
X = X.applymap(ifelse)
X = X.apply(rms_norm, axis=1)
X = np.array(X)

In [20]:
# X = [[0], [1], [2], [3]]
# y = [0, 0, 1, 1]

# Plätte 2D Bild in einen Vektor:
# Reshape behält die Anzahl Element in der ersten Dimension (len(X_orig) -> #Bilder)
# die restlichen Zellen des Arrays (-1 -> Pixel) bekommen alle ihre eigene Dimension
# X_p_test = X_test.reshape(len(X_test), -1).astype('float64')

# # Dimensionen um den Mittelpunkt zentrieren
# preproccessing = StandardScaler()
# X_p_test = preproccessing.fit_transform(X_p_test)

print ("Originaldaten:")
print("Shape: {}, Mean: {:f}, STD: {:f}".format(X_test.shape, np.mean(X_test), np.std(X_test)))

print ("Vorbereitete Daten:")
print("Shape: {}, Mean: {:f}, STD: {:f}".format(X.shape, np.mean(X), np.std(X)))

from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=5, n_jobs=-1, weights='distance')
neigh.fit(H_new, y_train)

# print(neigh.predict([[1.1]]))

# print(neigh.predict_proba([[0.9]]))

Originaldaten:
Shape: (10000, 28, 28), Mean: 33.791224, STD: 79.172463
Vorbereitete Daten:
Shape: (10000, 784), Mean: 0.398067, STD: 0.916661


KNeighborsClassifier(n_jobs=-1, weights='distance')

Back Activation of Test Data

In [21]:
XT = X.transpose()
print(f'shape of X_p_train {X.shape} and X_p_train transposed {XT.shape}')

reg = LinearRegression().fit(W, XT)
print(reg.score(W, XT))
XT_pred = reg.predict(W)

results['MAE_TEST_BA'] = round(mean_absolute_error(XT_pred, XT), 3)
results['MSE_TEST_BA'] = round(mean_squared_error(XT_pred, XT), 3)
results['R2_TEST_BA'] = round(r2_score(XT_pred, XT, multioutput="variance_weighted"), 3)

print(f'MAE {mean_absolute_error(XT_pred, XT)}')
print(f'MSE {mean_squared_error(XT_pred, XT)}')
print(f'R2 {r2_score(XT_pred, XT)}')
print(f'R2 vw {r2_score(XT_pred, XT, multioutput="variance_weighted")}')
print(f'R2 ua {r2_score(XT_pred, XT, multioutput="uniform_average")}')

H_test = reg.coef_
print(H_test.shape)
HI_test = reg.intercept_
print(HI_test.shape)

shape of X_p_train (10000, 784) and X_p_train transposed (784, 10000)
0.3931287617795535
MAE 0.5172530397145618
MSE 0.5066449049643522
R2 -0.7898492137891091
R2 vw -0.5336500135270926
R2 ua -0.7898492137891091
(10000, 10)
(10000,)


In [22]:
# X = H_new_train.reshape(len(H_new_train), -1).astype('int')
H_test = pd.DataFrame(H_test)
# H_new = H_new.applymap(ifelse)
H_test = H_test.apply(rms_norm, axis=1)
H_test = np.array(H_test)

In [25]:
# Predicting the Test set results
y_pred = neigh.predict(H_test)


KeyboardInterrupt: 

In [34]:
y1_pred = y_pred
df_y1 = pd.DataFrame(y_pred)
df_y1[1] = y1_pred
df_y1 

0  1
0     7  7
1     2  2
2     1  1
3     0  0
4     4  4
...  .. ..
9995  2  2
9996  3  3
9997  4  4
9998  5  5
9999  6  6

[10000 rows x 2 columns]

In [58]:
# y_prob = neigh.predict_proba(H_test)

In [59]:
# print(y_prob[0])

In [60]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 974    0    0    0    0    1    4    1    0    0]
 [   0 1128    3    0    3    0    1    0    0    0]
 [  10    2  994    3    0    0    0   12   10    1]
 [   3    0    8  964    1   10    0    7   13    4]
 [   2    4    1    0  941    0    7    2    2   23]
 [   4    0    1   12    3  844   14    0   12    2]
 [   6    4    0    0    1    1  945    0    1    0]
 [   2   11    5    0    2    0    1  994    0   13]
 [  11    2    2    8    2    2    5    3  934    5]
 [   8    5    2    6    7    2    1   11    2  965]]


In [61]:
from sklearn.metrics import accuracy_score, classification_report

results['ACCURACY_SCORE'] = accuracy_score(y_test, y_pred)
results['DICT_REPORT'] = str(classification_report(y_test, y_pred, output_dict=True))
# results['DICT_REPORT'] = ''

print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9683
              precision    recall  f1-score   support

           0       0.95      0.99      0.97       980
           1       0.98      0.99      0.98      1135
           2       0.98      0.96      0.97      1032
           3       0.97      0.95      0.96      1010
           4       0.98      0.96      0.97       982
           5       0.98      0.95      0.96       892
           6       0.97      0.99      0.98       958
           7       0.97      0.97      0.97      1028
           8       0.96      0.96      0.96       974
           9       0.95      0.96      0.95      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000



In [13]:
prot_row(results)

FileNotFoundError: [Errno 2] No such file or directory: '/content/sample_data/M-Net_Protocol.xlsx'

In [63]:
pd.DataFrame([results])

TIMESTAMP  ...              MSG
0 2020-12-26 21:42:11.050776  ...  M-Net on python

[1 rows x 20 columns]

In [64]:
results

{'ACCURACY_SCORE': 0.9683,
 'DICT_REPORT': "{'0': {'precision': 0.9549019607843138, 'recall': 0.9938775510204082, 'f1-score': 0.974, 'support': 980}, '1': {'precision': 0.9757785467128027, 'recall': 0.9938325991189427, 'f1-score': 0.9847228284591881, 'support': 1135}, '2': {'precision': 0.9783464566929134, 'recall': 0.9631782945736435, 'f1-score': 0.9707031250000001, 'support': 1032}, '3': {'precision': 0.9707955689828801, 'recall': 0.9544554455445544, 'f1-score': 0.9625561657513728, 'support': 1010}, '4': {'precision': 0.9802083333333333, 'recall': 0.9582484725050916, 'f1-score': 0.9691040164778579, 'support': 982}, '5': {'precision': 0.9813953488372092, 'recall': 0.9461883408071748, 'f1-score': 0.9634703196347031, 'support': 892}, '6': {'precision': 0.9662576687116564, 'recall': 0.9864300626304802, 'f1-score': 0.9762396694214875, 'support': 958}, '7': {'precision': 0.9650485436893204, 'recall': 0.9669260700389105, 'f1-score': 0.9659863945578231, 'support': 1028}, '8': {'precision': 0